### ISSUE TITLE
skatekey.net preview site is down

### ISSUE THREAD

**Issue by Cauchon** [makitso/custom-css#1]
https://skatekey.net/

Preview site is showing:
`Index file not found
We're sorry: the Web server could not find an index file in the "/" directory.

Index files should have one of the following lowercase names:

index.html
index.htm
index.shtml
index.php
default.html
default.htm
home.html
home.htm
Please check that a file with one of these lowercase names exists, then try again.

If this is your Web site and an index file exists, check the permissions of the file and the "/" directory. Both of them should be "world-readable" — directories should be "mode 0755 (rwxr-xr-x)" and files should be "mode 0644 (rw-r--r--)".

If you're still having trouble, this web page will probably help.`

**Comment by makitso** [comment]
Corrected
