### ISSUE TITLE
module does not work together with JustBlack palette of JustLight

### ISSUE THREAD

**Issue by hartenthaler** [makitso/custom-css#4]
please see https://github.com/JustCarmen/webtrees-theme-justlight/issues/90

**Comment by makitso** [comment]
Hermann, a link to your site please.

**Comment by hartenthaler** [comment]
Thank you! https://ahnen.hartenthaler.eu

**Comment by makitso** [comment]
Try removing lines 36-41 of custom.css and let me know if that fixes your problem.
![image](https://user-images.githubusercontent.com/5147603/132094753-535e76de-9859-4d65-ab9c-0777cb359938.png)

**Comment by hartenthaler** [comment]
After Download of newest version: It Looks perfect now. Thank you!
