### ISSUE TITLE
General Problem

### ISSUE THREAD

**Issue by hartenthaler** [makitso/custom-css#6]
I like to update my existing custom module "custom-css".

1. There are no releases of this module, so I downloaded the main development version
2. There is no folder "... disable" that can be renamed.
3. There is a folder custom-css that cannot be opened because it is no zip file.

**Comment by makitso** [comment]
I just downloaded the custom-css.zip file and unzipped it into a test directory.  All the files are there.  I would recommend that you do this step first, then rename the folder, and then copy the folder to the modules_v4 folder.

**Comment by hartenthaler** [comment]
I clicked on the green button "code", then selected "Download zip", then got a local file "custom-css-master.zip". Then I opened_ it and moved the folder custon-css-master to an unzipped local folder. Then I was lost. Maybe it would help if you "release" a new version as most of the custom modules are doing it.

**Comment by makitso** [comment]
`Then I opened_ it and moved the folder custon-css-master to an unzipped local folder`
The unzip should allow you to extract to some temporary folder.
Once this is complete you will have a folder named custom-css.disabled.  Move this folder and its contents to the webtrees modules_v4 folder.
Then rename the custom-css.disabled folder to custom-css

**Comment by hartenthaler** [comment]
I'm sorry, but when I try to open the custom-css.zip which was extracted from the custom-css-master.zip to a local temporary folder then I get an error message that the custom-css.zip is an invalid zip file. I'm using Windows 11 Pro. Maybe there is a problem with zip inside zip.
The steps you described (extract, move to webtrees folder modules_v4, rename) are clear.

**Comment by hartenthaler** [comment]
Problem solved: I opened https://github.com/makitso/custom-css/blob/master/custom-css.zip in the browser. Then I selected "Open this file in GitHub Desktop". Then I got the custom-css.disabled and finished the procedure successfully as you had described it.

**Comment by makitso** [comment]
I see the problem, I will try and figure out what is going on.
Edit:  I updated the download instructions.
