### ISSUE TITLE
latest release seems 1.0.13 in stead of 1.0.14

### ISSUE THREAD

**Issue by Joppla** [makitso/custom-css#8]
The file of the latest release is named 1.0.13 and not the suspected 1.0.14. Is it only the description or also the content?

![afbeelding](https://user-images.githubusercontent.com/25467829/206566711-65340f14-5930-4817-8644-ed28c5fdd5a7.png)

**Comment by makitso** [comment]
Sorry, not the best with understanding github.  Should be fixed now.
